### ISSUE TITLE
[FE] 제한 사항 보완

### ISSUE THREAD

**Issue by gunoc** [foody-moody/foodymoody#134]
# TASK
- [x] #140
- [x] uuid생성 패키지 삭제 => crypto로 변경
- [x] z-index조정
- [x] comment item에 대댓글 버튼 추가
- [x] 프로필에 팔로우 버튼 추가
- [x] comment 이모지버튼 추가
