### ISSUE TITLE
[BE] 회원 테스트 구현

### ISSUE THREAD

**Issue by sejeongsong** [foody-moody/foodymoody#25]
# TASK
- [ ] 회원 가입
- [ ] 회원 탈퇴
- [ ] 회원 정보 수정
- [ ] 회원 비번 수정
- [ ] 나의 프로필 조회
