### ISSUE TITLE
[BE] 회원, 이미지, 인증/인가 코딩 스타일 리팩토링

### ISSUE THREAD

**Issue by sejeongsong** [foody-moody/foodymoody#313]
# TASK
- [x] 패키지 구조 리팩토링
- [ ] 서비스, 컨트롤러 기능별로 분리
- [x] `@Deprecated`된 코드 사용하지 않도록 수정
- [x] 요청, 응답의 id를 BaseId 타입으로 수정
- [ ] 테스트코드 네이밍이 일관적이도록 수정
