### ISSUE TITLE
[FE] 알림 관련 작업

### ISSUE THREAD

**Issue by lolWK** [foody-moody/foodymoody#331]
# TASK
- [x] 알림 페이지 버튼 api 붙이기
  - [x] 전체 확인
  - [x] 전체 삭제
  - [x] 개별 확인
- [x] 알림 클릭 시 페이지 이동 및 프로필 이동
- [x] 알림 설정 페이지 UI
  - [x] on/off 컴포넌트 만들기
- [x] 알림 설정 api 붙이기
