### ISSUE TITLE
[FE] 가게정보

### ISSUE THREAD

**Issue by gunoc** [foody-moody/foodymoody#362]
# TASK
- [ ] api 선정 [네이버, 카카오]
- [ ] [FE] 가게 정보 페이지 UI
- [ ] [FE] 가게 정보 페이지 컴포넌트 
- [ ] [FE] 가게 검색 input 연결
- [ ] [FE] 기능 연동
