### ISSUE TITLE
[BE] 컬렉션 리펙토링

### ISSUE THREAD

**Issue by AlbertImKr** [foody-moody/foodymoody#381]
# TASK
- [x] API 주소 정리
- [x] 컬렉션 만들 때 피드 등록 삭제
- [x] 피드 댓글 테스트 구현(대댓글 포함)
- [x] 피드 컬렉션 테스트 구현
