### ISSUE TITLE
[FE] liked반영 확인

### ISSUE THREAD

**Issue by gunoc** [foody-moody/foodymoody#460]
# TASK
- [x] 댓글 liked반영 확인
- [x] 피드 liked반영 확인
- [x] 유효하지 않은 이미지 url
