### ISSUE TITLE
[BE]  코드 리팩토링

### ISSUE THREAD

**Issue by AlbertImKr** [foody-moody/foodymoody#476]
# TASK
- [x] 일림
- [x] 피드 커멘트
- [x] 피드 컬렉션
- [x] 피드 커멘트 좋아요
- [x] 피드 댓글 좋아요 카운트
- [x] 피드 댓글 대댓글 좋아요
- [x] 피드 댓글 대댓글 좋아요 카운트
- [x] 피드 컬렉션 댓글
- [x] 피드 컬렉션 댓글 좋아요
- [x] 피드 컬렉션 댓글 좋아요 카운트
- [x] 피드 컬렉션 댓글 대댓글 
- [x] 피드 컬렉션 댓글 대댓글  좋아요
- [x] 피드 컬렉션 댓글 대댓글  좋아요 카운트
- [x] 맴버 알림 설정
