### ISSUE TITLE
[BE] 프로젝트 환경 세팅

### ISSUE THREAD

**Issue by won4885** [foody-moody/foodymoody#5]
# TASK
- [x] Rest Docs 세팅
- [x] Rest Assured 세팅
- [x] Code Style 통일
