### ISSUE TITLE
[BE] 오류 수정

### ISSUE THREAD

**Issue by AlbertImKr** [foody-moody/foodymoody#542]
# TASK
- [x] 팔로우 알림 오류 수정 (팔로우 한 멤버가 알림을 받아야 한다.)
- [x] 컬렉션 피드리스트에 피드 추가, 삭제 기능
- [x] 대댓글 개수 및 대댓글 존재 여부 동기화 문제 및 대댓글 삭제 문제 해결
- [x] SSE count 0을 보내지 않은 문제
