### ISSUE TITLE
[BE] 피드 컬렉션 기본 썸네일url 변경

### ISSUE THREAD

**Issue by AlbertImKr** [foody-moody/foodymoody#554]
# TASK
- [x] 피드 컬렉션 기본 썸네일url 변경
- [x] 컬렉션 좋아요 조회 오류 수정
- [x] 컬렉션 좋아요 중복 오류
- [x] 컬렉션 디테일 조회시 store 정보 함께 조회
